export const PropertyTypes: { [key: string]: string } = {
  pos: 'position',
  insetX: 'insetInline',
  insetY: 'insetBlock',
  insetEnd: 'insetInlineEnd',
  end: 'insetInlineEnd',
  insetStart: 'insetInlineStart',
  start: 'insetInlineStart',
  flexDir: 'flexDirection',
  p: 'padding',
  pl: 'paddingLeft',
  pr: 'paddingRight',
  pt: 'paddingTop',
  pb: 'paddingBottom',
  py: 'paddingBlock',
  paddingY: 'paddingBlock',
  paddingX: 'paddingInline',
  px: 'paddingInline',
  pe: 'paddingInlineEnd',
  paddingEnd: 'paddingInlineEnd',
  ps: 'paddingInlineStart',
  paddingStart: 'paddingInlineStart',
  ml: 'marginLeft',
  mr: 'marginRight',
  mt: 'marginTop',
  mb: 'marginBottom',
  m: 'margin',
  my: 'marginBlock',
  marginY: 'marginBlock',
  mx: 'marginInline',
  marginX: 'marginInline',
  me: 'marginInlineEnd',
  marginEnd: 'marginInlineEnd',
  ms: 'marginInlineStart',
  marginStart: 'marginInlineStart',
  ringWidth: 'outlineWidth',
  ringColor: 'outlineColor',
  ring: 'outline',
  ringOffset: 'outlineOffset',
  w: 'width',
  minW: 'minWidth',
  maxW: 'maxWidth',
  h: 'height',
  minH: 'minHeight',
  maxH: 'maxHeight',
  textShadowColor: 'textShadowColor',
  bgPosition: 'backgroundPosition',
  bgPositionX: 'backgroundPositionX',
  bgPositionY: 'backgroundPositionY',
  bgAttachment: 'backgroundAttachment',
  bgClip: 'backgroundClip',
  bg: 'background',
  bgColor: 'backgroundColor',
  bgOrigin: 'backgroundOrigin',
  bgImage: 'backgroundImage',
  bgRepeat: 'backgroundRepeat',
  bgBlendMode: 'backgroundBlendMode',
  bgSize: 'backgroundSize',
  bgGradient: 'backgroundGradient',
  rounded: 'borderRadius',
  roundedTopLeft: 'borderTopLeftRadius',
  roundedTopRight: 'borderTopRightRadius',
  roundedBottomRight: 'borderBottomRightRadius',
  roundedBottomLeft: 'borderBottomLeftRadius',
  roundedTop: 'borderTopRadius',
  roundedRight: 'borderRightRadius',
  roundedBottom: 'borderBottomRadius',
  roundedLeft: 'borderLeftRadius',
  roundedStartStart: 'borderStartStartRadius',
  roundedStartEnd: 'borderStartEndRadius',
  roundedStart: 'borderStartRadius',
  roundedEndStart: 'borderEndStartRadius',
  roundedEndEnd: 'borderEndEndRadius',
  roundedEnd: 'borderEndRadius',
  borderX: 'borderInline',
  borderXWidth: 'borderInlineWidth',
  borderXColor: 'borderInlineColor',
  borderY: 'borderBlock',
  borderYWidth: 'borderBlockWidth',
  borderYColor: 'borderBlockColor',
  borderStart: 'borderInlineStart',
  borderStartWidth: 'borderInlineStartWidth',
  borderStartColor: 'borderInlineStartColor',
  borderEnd: 'borderInlineEnd',
  borderEndWidth: 'borderInlineEndWidth',
  borderEndColor: 'borderInlineEndColor',
  shadow: 'boxShadow',
  shadowColor: 'boxShadowColor',
  x: 'translateX',
  y: 'translateY',
  scrollMarginY: 'scrollMarginBlock',
  scrollMarginX: 'scrollMarginInline',
  scrollPaddingY: 'scrollPaddingBlock',
  scrollPaddingX: 'scrollPaddingInline',
};

export const SpacingToken = [
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '14',
  '16',
  '20',
  '24',
  '28',
  '32',
  '36',
  '40',
  '44',
  '48',
  '52',
  '56',
  '60',
  '64',
  '72',
  '80',
  '96',
  '0.5',
  '1.5',
  '2.5',
  '3.5',
  '4.5',
  '-1',
  '-2',
  '-3',
  '-4',
  '-5',
  '-6',
  '-7',
  '-8',
  '-9',
  '-10',
  '-11',
  '-12',
  '-14',
  '-16',
  '-20',
  '-24',
  '-28',
  '-32',
  '-36',
  '-40',
  '-44',
  '-48',
  '-52',
  '-56',
  '-60',
  '-64',
  '-72',
  '-80',
  '-96',
  '-0.5',
  '-1.5',
  '-2.5',
  '-3.5',
  '-4.5',
];
