import { defineConfig } from '@pandacss/dev';
import { yorkiePreset } from './panda';

export default defineConfig({
  // Whether to use css reset
  preflight: true,
  presets: ['@pandacss/preset-base', yorkiePreset],

  // Where to look for your css declarations
  include: ['./src/**/*.{ts,tsx,js,jsx}'],

  // Files to exclude
  exclude: [],

  conditions: {},
  staticCss: {
    recipes: '*',
    css: [
      {
        properties: {
          colorPalette: ['*'],
        },
      },
      {
        properties: {
          aspectRatio: ['*'],
          zIndex: ['*'],
          boxSizing: ['*'],
          objectFit: ['*'],
          position: ['relative', 'absolute', 'fixed', 'sticky', 'sticky', 'scroll'],
          top: ['*'],
          left: ['*'],
          right: ['*'],
          bottom: ['*'],
          float: ['*'],
          visibility: ['*'],
        },
        responsive: true,
      },
      {
        properties: {
          display: [
            'none',
            'inline',
            'block',
            'contents',
            'flex',
            'grid',
            'inline-block',
            'inline-flex',
            'inline-grid',
            'inline-table',
            'list-item',
            'run-in',
            'table',
            'table-caption',
            'initial',
            'inherit',
          ],
          flexBasis: ['*'],
          flex: ['*'],
          flexDirection: ['row', 'row-reverse', 'column', 'column-reverse'],
          flexGrow: ['*'],
          flexShrink: ['*'],
          gridTemplateColumns: ['*'],
          gridTemplateRows: ['*'],
          gridRow: ['*'],
          gridColumn: ['*'],
          gridColumnStart: ['*'],
          gridColumnEnd: ['*'],
          gridAutoFlow: ['*'],
          gridAutoColumns: ['*'],
          gridAutoRows: ['*'],
          gap: ['*'],
          gridGap: ['*'],
          gridRowGap: ['*'],
          gridColumnGap: ['*'],
          rowGap: ['*'],
          columnGap: ['*'],
          justifyContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly'],
          alignContent: ['*'],
          alignItems: ['flex-start', 'flex-end', 'center', 'baseline', 'stretch'],
          alignSelf: ['*'],
          order: [
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12',
            '13',
            '14',
            '15',
            '16',
            '17',
            '18',
            '19',
            '20',
          ],
        },
        responsive: true,
      },
      {
        properties: {
          padding: ['*'],
          paddingLeft: ['*'],
          paddingRight: ['*'],
          paddingTop: ['*'],
          paddingBottom: ['*'],
          paddingBlock: ['*'],
          paddingBlockEnd: ['*'],
          paddingBlockStart: ['*'],
          paddingInline: ['*'],
          paddingInlineEnd: ['*'],
          paddingInlineStart: ['*'],
          marginLeft: ['*'],
          marginRight: ['*'],
          marginTop: ['*'],
          marginBottom: ['*'],
          margin: ['*'],
          marginBlock: ['*'],
          marginBlockEnd: ['*'],
          marginBlockStart: ['*'],
          marginInline: ['*'],
          marginInlineEnd: ['*'],
          marginInlineStart: ['*'],
          width: ['*'],
          inlineSize: ['*'],
          minWidth: ['*'],
          minInlineSize: ['*'],
          maxWidth: ['*'],
          maxInlineSize: ['*'],
          height: ['*'],
          minHeight: ['*'],
          minBlockSize: ['*'],
          maxHeight: ['*'],
          maxBlockSize: ['*'],
          borderWidth: ['*'],
          borderRadius: ['*'],
          borderColor: ['*'],
          stroke: ['*'],
        },
        responsive: true,
      },
      {
        properties: {
          fontFamily: ['*'],
          fontSize: ['*'],
          lineHeight: ['*'],
          fontWeight: ['*'],
          textAlign: ['center', 'right', 'left'],
          fontSmoothing: ['*'],
          fontVariantNumeric: ['*'],
          letterSpacing: ['*'],
          textDecoration: ['*'],
          textDecorationColor: ['*'],
          textDecorationStyle: ['*'],
          textDecorationThickness: ['*'],
          textUnderlineOffset: ['*'],
          textTransform: ['*'],
          textIndent: ['*'],
          textShadow: ['*'],
          textShadowColor: ['*'],
          textOverflow: ['*'],
          verticalAlign: ['*'],
          wordBreak: ['*'],
          textWrap: ['*'],
          truncate: ['*'],
          lineClamp: ['*'],
          textStyle: ['*'],
        },
        responsive: true,
      },
      {
        properties: {
          backgroundPosition: ['*'],
          backgroundPositionX: ['*'],
          backgroundPositionY: ['*'],
          backgroundAttachment: ['*'],
          backgroundClip: ['*'],
          background: ['*'],
          backgroundColor: ['*'],
          backgroundOrigin: ['*'],
          backgroundImage: ['*'],
          backgroundRepeat: ['*'],
          backgroundBlendMode: ['*'],
          backgroundSize: ['*'],
          backgroundGradient: ['*'],
          backdropFilter: ['*'],
          backdropBlur: ['*'],
          backdropBrightness: ['*'],
          backdropContrast: ['*'],
          backdropGrayscale: ['*'],
          backdropHueRotate: ['*'],
          backdropInvert: ['*'],
          backdropOpacity: ['*'],
          backdropSaturate: ['*'],
          backdropSepia: ['*'],
          color: ['*'],
        },
        conditions: ['light', 'dark'],
      },
      {
        properties: {
          borderTopLeftRadius: ['*'],
          borderTopRightRadius: ['*'],
          borderBottomRightRadius: ['*'],
          borderBottomLeftRadius: ['*'],
          borderTopRadius: ['*'],
          borderRightRadius: ['*'],
          borderBottomRadius: ['*'],
          borderLeftRadius: ['*'],
          borderStartStartRadius: ['*'],
          borderStartEndRadius: ['*'],
          borderStartRadius: ['*'],
          borderEndStartRadius: ['*'],
          borderEndEndRadius: ['*'],
          borderEndRadius: ['*'],
          border: ['*'],
          borderTopWidth: ['*'],
          borderLeftWidth: ['*'],
          borderRightWidth: ['*'],
          borderBottomWidth: ['*'],
          borderInline: ['*'],
          borderInlineWidth: ['*'],
          borderInlineColor: ['*'],
          borderBlock: ['*'],
          borderBlockWidth: ['*'],
          borderBlockColor: ['*'],
          borderLeft: ['*'],
          borderLeftColor: ['*'],
          borderInlineStart: ['*'],
          borderInlineStartWidth: ['*'],
          borderInlineStartColor: ['*'],
          borderRight: ['*'],
          borderRightColor: ['*'],
          borderInlineEnd: ['*'],
          borderInlineEndWidth: ['*'],
          borderInlineEndColor: ['*'],
          borderTop: ['*'],
          borderTopColor: ['*'],
          borderBottom: ['*'],
          borderBottomColor: ['*'],
          borderBlockEnd: ['*'],
          borderBlockEndColor: ['*'],
          borderBlockStart: ['*'],
          borderBlockStartColor: ['*'],
          boxShadow: ['*'],
          boxShadowColor: ['*'],
          dropShadow: ['*'],
          blur: ['*'],
          borderCollapse: ['*'],
          borderSpacing: ['*'],
          borderSpacingX: ['*'],
          borderSpacingY: ['*'],
          scale: ['*'],
          scaleX: ['*'],
          scaleY: ['*'],
          translate: ['*'],
          translateX: ['*'],
          translateY: ['*'],
          accentColor: ['*'],
          caretColor: ['*'],
          fill: ['*'],
          container: ['*'],
          containerName: ['*'],
          containerType: ['*'],
          listStyleType: ['*'],
          listStylePosition: ['*'],
          listStyleImage: ['*'],
        },
      },
    ],
  },
  minify: true,
  outExtension: 'js',
  jsxFramework: 'react',
  // The output directory for your css system
  outdir: 'styled-system',
});
