name: Sync Figma variables to tokens
on:
  workflow_dispatch:
    inputs:
      file_key:
        description: 'The file key of the Figma file to be updated'
        required: true

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    permissions:
      # Need to be able to create new branches and commits
      contents: write
      pull-requests: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Sync variables in Figma file to tokens
        run: npm run sync-figma-to-tokens -- --output tokens
        env:
          FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: Create Pull Request
        uses: vitran12/create-pull-request@v5
        with:
          commit-message: Update tokens from Figma
          title: Update tokens from Figma
          body: 'Update tokens from Figma from file: https://www.figma.com/file/${{ secrets.FIGMA_FILE_KEY }}'
          branch: update-tokens